### ISSUE TITLE
"increased Quantity of Items found during flask effect" missing

### ISSUE THREAD

**Issue by marshauf** [thirdy/durian#42]
"increased Quantity of Items found during flask effect" mod is missing

**Comment by thirdy** [comment]
Hi, atm, only the common mods are defined, since it's a bit of an effort to define them all. Well, it's more of a hesitation from me not knowing what's the best "PoE jargon" to use for these mods I'm not familiar of.

But here's how to add that:

https://www.reddit.com/r/pathofexile/comments/3z9ms6/durian_v05_mod_affix_tier_item_art_improved_sound/cyknvc8

You can also make a pull request, so it's gonna be in the program by default on the next release. Cheers!

**Comment by marshauf** [comment]
Yes, I did that already for iiq and iqqf. iiq worked but iqqf did not. I found the problem I copied the mod description from the wiki which had flask with a lowercase f but Durian requires an uppercase.
